In [ ]:
import json
import pandas
pandas.set_option("display.latex.repr",False)
import matplotlib

In [52]:
si_preds = {}
pi_preds = {}
with open("std_predictions_si.json","r") as _f:
    si_preds = json.load(_f)
with open("std_predictions_pi.json","r") as _f:
    pi_preds = json.load(_f)

In [60]:
from IPython.display import display, HTML
for _binNo in si_preds.keys():
    print('Bin number %s' % _binNo)
    si_frame = pandas.DataFrame(si_preds[_binNo]).transpose()
    display(HTML(pandas.DataFrame(si_frame).to_html()))

Bin number 0

Bin number 1

Bin number 2

Bin number 3

Bin number 4

Bin number 5

Bin number 6

Bin number 7

Bin number 8

Bin number 9

In [61]:
for _binNo in pi_preds.keys():
    print('Bin number %s' % _binNo)
    pi_frame = pandas.DataFrame(pi_preds[_binNo]).transpose()
    display(HTML(pandas.DataFrame(pi_frame).to_html()))

Bin number 0

Bin number 1

Bin number 2

Bin number 3

Bin number 4

Bin number 5

Bin number 6

Bin number 7

Bin number 8

Bin number 9